In [ ]:
#https://lol.fandom.com/wiki/Help:Leaguepedia_API
""" 
    This is the website I used to figure out how to query API from Leaguepedia (storing all match statistics)
"""
import mwclient

#This is the LeaguePedia website that stores all match and team statistics
site = mwclient.Site('lol.fandom.com', path='/')


"""
    I searched for a quicker way to iterate for loops because it took too long to run
"""
#https://github.com/tqdm/tqdm 
from tqdm.notebook import tqdm

#pre-set the leagues I want to look at - all those that will qualify to worlds
#leagues=['GPL','IWCQ','WCS','LCS','LEC','LCK','LPL','CBLOL','LCL','LJL','LLA','OPL','PCS','VCS','TCL','LMS','LST','NA LCS','EU LCS','LLN','CLS']
#leagues=['LCS','LEC','LCK','LPL','CBLOL','LJL','LLA','PCS','VCS']
leagues=['LCK']

#create an empty list to store my dataset
results = []

#for loop to create my data base of match stats
for league in tqdm(leagues):
    off=0
    
    #while loop to retrive data thruogh API
    while True:
        #API query
        response = site.api('cargoquery',
                            offset=str(off),
                            
                            limit="500",
                            
                            #retrive tables
                            tables = "ScoreboardGames=SG, ScoreboardPlayers=SP,Tournaments=T, Leagues=L",
                            
                            #retrive fields as columns
                            fields="T.Name=Tournament,\
                                    L.League_Short=League,\
                                    SP.Link,\
                                    SG.DateTime_UTC, SG.Gamelength, SG.Team1, SG.Team2, SG.Team1Score, SG.Team2Score", 
                            
                            #set condition (only include specified leagues)
                            where = 'L.League_Short = "'+league+'"',
                            
                            #similar to vlookup in the web pages
                            join_on = "SG.OverviewPage=T.OverviewPage, T.League = L.League, SP.MatchId=SG.MatchId")
        
        #add to database
        results += response["cargoquery"] 
        
        #speed
        off=off+500
        if(len(response["cargoquery"])<500): break
        

#import pandas as pd
#df_Scoreboard = pd.DataFrame([ a['title'] for a in results ])
#df_Scoreboard = df_Scoreboard.drop("DateTime UTC__precision", axis=1)
#df_Scoreboard.sort_values("DateTime UTC")
#df_Scoreboard.head()
#df_Scoreboard.to_csv("Scoreboard.csv")

  0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
import pandas as pd
df_Scoreboard = pd.DataFrame([ a['title'] for a in results ])
df_Scoreboard = df_Scoreboard.drop("DateTime UTC__precision", axis=1)
df_Scoreboard.sort_values("DateTime UTC")
df_Scoreboard.head()
#df_Scoreboard.to_csv("Scoreboard.csv")

In [16]:
#https://lol.fandom.com/wiki/Help:Leaguepedia_API
""" 
    This is the website I used to figure out how to query API from Leaguepedia (storing all match statistics)
"""
import mwclient

#This is the LeaguePedia website that stores all match and team statistics
site = mwclient.Site('lol.fandom.com', path='/')


"""
    I searched for a quicker way to iterate for loops because it took too long to run
"""
#https://github.com/tqdm/tqdm 
from tqdm.notebook import tqdm

#pre-set the leagues I want to look at - all those that will qualify to worlds
#leagues=['LCS','LEC','LCK','LPL','CBLOL','LJL','LLA','PCS','VCS']
leagues=['LCK']

#create an empty list to store my dataset
results = []

#for loop to create my data base of match stats
for league in tqdm(leagues):
    off=0
    
    #while loop to retrive data thruogh API
    while True:
        #API query
        response = site.api('cargoquery',
                            offset=str(off),
                            
                            limit="max",
                            
                            #retrive tables
                            tables = "Teams=T, Players=P",
                            
                            #retrive fields as columns
                            fields="P.Team=Team, P.ID=ID, P.Nationality, P.Country,P.Birthdate,\
                                    T.Region=Region, T.Short", 
                            
                            #set condition 
                            #where = 'T.Name = P.Team',
                            
                            #similar to vlookup in the web pages
                            join_on = "T.Name = P.Team")
        
        #add to database
        results += response["cargoquery"] 
        
        #speed
        off=off+500
        if(len(response["cargoquery"])<500): break

        
        
import pandas as pd
df_Players = pd.DataFrame([ a['title'] for a in results ])

#drop birthdate precision
df_Players = df_Players.drop("Birthdate__precision", axis=1)

df_Players.head()
#df_Players.to_csv("Players.csv")

  0%|          | 0/1 [00:00<?, ?it/s]

   Team    ID Nationality Country Birthdate   Region Short
0  None  None        None    None      None  Vietnam    TF
1  None  None        None    None      None    Korea  DK.A
2  None  None        None    None      None     EMEA   YTR
3  None  None        None    None      None   Europe  RIFT
4  None  None        None    None      None   Europe  NERO

In [20]:
df_stats = df_Scoreboard.merge(df_Players, left_on = 'Team1', right_on = 'Team', how = 'left')
df_stats.head()
df_stats.to_csv("Merged.csv")

In [ ]:
#############################################################################################################################
#############################################################################################################################
#############################################################################################################################
#############################################################################################################################

# Imported all leagues scoreboard games data

In [125]:
#https://lol.fandom.com/wiki/Help:Leaguepedia_API
""" 
    This is the website I used to figure out how to query API from Leaguepedia (storing all match statistics)
"""
import mwclient

#This is the LeaguePedia website that stores all match and team statistics
site = mwclient.Site('lol.fandom.com', path='/')


"""
    I searched for a quicker way to iterate for loops because it took too long to run
"""
#https://github.com/tqdm/tqdm 
from tqdm.notebook import tqdm

#pre-set the leagues I want to look at - all those that will qualify to worlds
leagues=['GPL','IWCQ','WCS','LCS','LEC','LCK','LPL','CBLOL','LCL','LJL','LLA','OPL','PCS','VCS','TCL','LMS','LST','NA LCS','EU LCS','LLN','CLS']


#create an empty list to store my dataset
results = []

#for loop to create my data base of match stats
for league in tqdm(leagues):
    off=0
    
    #while loop to retrive data thruogh API
    while True:
        #API query
        response = site.api('cargoquery',
                            offset=str(off),
                            
                            limit="max",
                            
                            #retrive tables
                            tables = "ScoreboardGames=SG,Tournaments=T, Leagues=L",
                            
                            #retrive fields as columns
                            fields="T.Name=Tournament,\
                                    L.League_Short=League,\
                                    SG.DateTime_UTC=Date, SG.Gamelength, SG.Team1, SG.Team2, SG.Team1Score, SG.Team2Score,SG.WinTeam", 
                            
                            #set condition (only include specified leagues)
                            where = 'L.League_Short = "'+league+'"',
                            
                            #similar to vlookup in the web pages
                            join_on = "SG.OverviewPage=T.OverviewPage, T.League = L.League")
        
        #add to database
        results += response["cargoquery"] 
        
        #speed
        off=off+500
        if(len(response["cargoquery"])<500): break

  0%|          | 0/21 [00:00<?, ?it/s]

# Convert to Panda DataFrame and Clean Data

In [129]:
#import pandas package
import pandas as pd

#convert to dataframe from dictionary
df_Scoreboard = pd.DataFrame([ a['title'] for a in results ])

#drop unused column
df_Scoreboard = df_Scoreboard.drop("Date__precision", axis=1)

#sort by date
df_Scoreboard.sort_values(by = "Date",inplace=True)

#split date and time
df_Scoreboard["Date"] = pd.to_datetime(df_Scoreboard["Date"])
df_Scoreboard["Year"]= df_Scoreboard["Date"].dt.year

#convert Team 1 & 2 score as integers
df_Scoreboard = df_Scoreboard.astype({'Team1Score':'int','Team2Score':'int'})

#preview first few rows
df_Scoreboard.head()

#save as csv
#df_Scoreboard.to_csv("Scoreboard.csv")

,Tournament,League,Date,Gamelength,Team1,Team2,Team1Score,Team2Score,WinTeam,Year
2127,Worlds Season 1,WCS,2011-06-18 08:30:00,45:09,against All authority,Epik Gamer,0,1,Epik Gamer,2011
2128,Worlds Season 1,WCS,2011-06-18 09:45:00,29:38,Fnatic,Team Pacific,1,0,Fnatic,2011
2130,Worlds Season 1,WCS,2011-06-18 11:00:00,41:18,against All authority,Fnatic,1,0,against All authority,2011
2129,Worlds Season 1,WCS,2011-06-18 11:00:00,28:55,Epik Gamer,Team Pacific,1,0,Epik Gamer,2011
2131,Worlds Season 1,WCS,2011-06-18 12:15:00,24:13,against All authority,Team Pacific,1,0,against All authority,2011

# Imported all teams region data

In [1]:
#https://lol.fandom.com/wiki/Help:Leaguepedia_API
""" 
    This is the website I used to figure out how to query API from Leaguepedia (storing all match statistics)
"""
import mwclient

#This is the LeaguePedia website that stores all match and team statistics
site = mwclient.Site('lol.fandom.com', path='/')


"""
    I searched for a quicker way to iterate for loops because it took too long to run
"""
#https://github.com/tqdm/tqdm 
from tqdm.notebook import tqdm

#pre-set the leagues I want to look at - all those that will qualify to worlds
leagues=['GPL','IWCQ','WCS','LCS','LEC','LCK','LPL','CBLOL','LCL','LJL','LLA','OPL','PCS','VCS','TCL','LMS','LST','NA LCS','EU LCS','LLN','CLS']


#create an empty list to store my dataset
results = []

#for loop to create my data base of match stats
for league in tqdm(leagues):
    off=0
    
    #while loop to retrive data thruogh API
    while True:
        #API query
        response = site.api("cargoquery",
                            offset=str(off),
                            
                            limit="max",
                            
                            #retrive tables
                            tables = "Teams=T",
                            
                            #retrive fields as columns
                            fields="T.Name=Team, T.Region=Region, T.Short=Team_abbr")
                            
        #add to database
        results += response["cargoquery"] 
        
        #speed
        off=off+500
        if(len(response["cargoquery"])<500): break

  0%|          | 0/21 [00:00<?, ?it/s]

# Convert to Panda DataFrame and Clean Data

In [2]:
import pandas as pd
df_TeamRegion = pd.DataFrame([ a['title'] for a in results ])

df_TeamRegion.head()
#df_TeamRegion.to_csv("TeamRegion.csv")

   Team  Region Team_abbr
0  None    EMEA       TTW
1  None  Europe    FYN.CH
2  None  Europe        GG
3  None  Europe       OPE
4  None  Europe       RFX

In [ ]:
#dictionary to match regions
dict_regions = {
    'Africa':'EMEA',
    'Brazil':'BR',
    'China':'CN',
    'CIS':'INT',
    'EMEA':'EMEA',
    'Europe':'EMEA',
    'International':'INT',
    'Japan':'JP',
    'Korea':'KR',
    'LAN':'INT',
    'LAS':'INT',
    'Latin America':'LAT',
    'LMS':'INT',
    'MENA':'INT',
    'North America':'NA',
    'Oceania':'PCS',
    'PCS':'PCS',
    'SEA':'PCS',
    'Turkey':'EMEA',
    'Vietnam':'VN'
}

def get_region_code(region):
    return dict_regions[region]

get_region_code(df_TeamRegion["Region"][2])

for index,row in df_TeamRegion["Region"].iterrows():
    df_TeamRegion["Region_code"] = df_TeamRegion["Region"].apply(get_region_code)
    
    
#df_regions = pd.DataFrame(dict_regions)
#df_regions.reset_index()
df_regions.head()
#df_regions.to_csv("TeamRegionCode.csv")

In [148]:
#############################################################################################################################

'EMEA'

In [132]:
df_team1 = df_Scoreboard.merge(df_Players, left_on = 'Team1', right_on = 'Team', how = 'left', suffixes = ['_T1'])
df_team1.head()
#df_team1.to_csv("Merged Team 1.csv")

,Tournament,League,Date,Gamelength,Team1,Team2,Team1Score,Team2Score,WinTeam,Year,Team,ID,Nationality,Country,Birthdate,Region,Short
0,Worlds Season 1,WCS,2011-06-18 08:30:00,45:09,against All authority,Epik Gamer,0,1,Epik Gamer,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Worlds Season 1,WCS,2011-06-18 09:45:00,29:38,Fnatic,Team Pacific,1,0,Fnatic,2011,Fnatic,Hiiva,None,Finland,1994-08-31,EMEA,FNC
2,Worlds Season 1,WCS,2011-06-18 09:45:00,29:38,Fnatic,Team Pacific,1,0,Fnatic,2011,Fnatic,Humanoid,None,Czech Republic,2000-03-14,EMEA,FNC
3,Worlds Season 1,WCS,2011-06-18 09:45:00,29:38,Fnatic,Team Pacific,1,0,Fnatic,2011,Fnatic,Jovirone,None,Brazil,1998-09-25,EMEA,FNC
4,Worlds Season 1,WCS,2011-06-18 09:45:00,29:38,Fnatic,Team Pacific,1,0,Fnatic,2011,Fnatic,Nightshare,None,Czech Republic,1994-06-06,EMEA,FNC

In [98]:
#create dictionary to match start and end of league season
#season dates found on Leaguepedia
dict_match_season = {
    2023:{'Start':'2022-11-11 00:00:00','End':'2023-10-01 00:00:00'},
    2022:{'Start':'2021-11-11 00:00:00','End':'2022-10-01 00:00:00'},  
    2021:{'Start':'2020-11-11 00:00:00','End':'2021-10-01 00:00:00'},  
    2020:{'Start':'2019-11-11 00:00:00','End':'2020-10-01 00:00:00'},  
    2019:{'Start':'2018-11-04 00:00:00','End':'2019-10-09 00:00:00'},
    2018:{'Start':'2017-11-05 00:00:00','End':'2018-10-08 00:00:00'},
    2017:{'Start':'2016-10-30 00:00:00','End':'2017-09-30 00:00:00'},
    2016:{'Start':'2015-10-30 00:00:00','End':'2016-09-30 00:00:00'},
    2015:{'Start':'2014-10-30 00:00:00','End':'2015-09-30 00:00:00'},
    2014:{'Start':'2013-10-30 00:00:00','End':'2014-09-30 00:00:00'},
    2013:{'Start':'2012-10-30 00:00:00','End':'2013-09-30 00:00:00'},
    2012:{'Start':'2011-10-30 00:00:00','End':'2012-09-30 00:00:00'},
}

In [99]:
#create dictionary for all match stats within the season 
dict_match_data_per_season=dict()
for date in dict_match_season:
    dict_match_data_per_season[date] = df_Scoreboard[
        (df_Scoreboard.Date>dict_match_season[date]['Start'])&
        (df_Scoreboard.Date<dict_match_season[date]['End'])]

In [103]:
#get match data per season
df_match_data_per_season = pd.DataFrame(dict_match_data_per_season[2015])
df_match_data_per_season.head()

,Tournament,League,Date,Gamelength,Team1,Team2,Team1Score,Team2Score,WinTeam,Year
27662,NA LCS 2015 Spring Expansion,NA LCS,2014-11-15 20:07:00,36:28,Team LoLPro,Fission Esports,1,0,Team LoLPro,2014
27663,NA LCS 2015 Spring Expansion,NA LCS,2014-11-15 20:30:00,24:00,Team Coast,Call Gaming,1,0,Team Coast,2014
27664,NA LCS 2015 Spring Expansion,NA LCS,2014-11-15 21:34:00,35:31,Call Gaming,Team Coast,0,2,Team Coast,2014
27665,NA LCS 2015 Spring Expansion,NA LCS,2014-11-15 22:53:00,38:18,Fission Esports,Team LoLPro,0,2,Team LoLPro,2014
27666,NA LCS 2015 Spring Expansion,NA LCS,2014-11-15 23:45:00,23:08,Enemy,Noble Truth,1,0,Enemy,2014

In [83]:
#get leagues - without duplicates
dict_match_data_per_season[2022]["League"].unique()

array(['VCS', 'LPL', 'LCK', 'LEC', 'LCS', 'TCL', 'CBLOL', 'LLA', 'LJL',
       'PCS', 'LCL', 'WCS'], dtype=object)

In [84]:
#because LoL changed the league names, I create a dictionary to match the old and new league names
#alias = {
dict_league_names = {
    'GPL': 'PCS', 
    'NA LCS': 'LCS', 
    'EU LCS': 'LEC', 
    'LPL': 'LPL', 
    'TCL': 'PCS', 
    'LJL': 'LJL', 
    'CBLOL': 'CBLOL',
    'LMS': 'PCS', 
    'OPL': 'OPL', 
    'CLS': 'LLA', 
    'LCK': 'LCK', 
    'LCL': 'LCL', 
    'LLN': 'LLA', 
    'VCS': 'PCS', 
    'LEC': 'LEC',
    'LLA': 'LLA', 
    'LCS': 'LCS', 
    'PCS': 'PCS',
    'LST': 'PCS'
}
list_regions = list(set([dict_league_names[name] for name in dict_league_names]))

In [ ]:
#create a dictionary for Worlds Stats 
dict_Worlds_data=dict()

#create a dictionary for Groups Data
dict_groups_data=dict()

#for all years in stats 2011 - 2022:
for year in range (2011, 2023):
    
    response = site.api('cargoquery',
                        limit="max",
                        tables = "MatchSchedule=M",
                        fields="M.Team1Final=Team1, M.Team2Final=Team2, M.Team1Score, M.Team2Score, M.Tab",
                        where = 'M.OverviewPage = "'+str(year)+' Season World Championship/Main Event"')
    
    #create dictionary for LoL Worlds Championship match stats
    dict_Worlds_data[year] = pd.DataFrame ( [ a['title'] for a in response['cargoquery'] ] )
    
    response = site.api('cargoquery',
                        limit="max",
                        tables = "TournamentGroups=T",
                        fields="T.Team, T.GroupName",
                        where = 'T.OverviewPage = "'+str(year)+' Season World Championship/Main Event"')
    
    #create dictionary for Groups Data
    dict_groups_data[year] = pd.DataFrame ( [ a['title'] for a in response['cargoquery'] ] )

In [117]:
dict_Worlds_data

{2011: Empty DataFrame
 Columns: []
 Index: [],
 2012: Empty DataFrame
 Columns: []
 Index: [],
 2013: Empty DataFrame
 Columns: []
 Index: [],
 2014: Empty DataFrame
 Columns: []
 Index: [],
 2015: Empty DataFrame
 Columns: []
 Index: [],
 2016: Empty DataFrame
 Columns: []
 Index: [],
 2017:                   Team1                Team2 Team1Score Team2Score  \
 0      ahq eSports Club               Cloud9          0          1
 1      ahq eSports Club        EDward Gaming          0          1
 2      ahq eSports Club        SK Telecom T1          1          0
 3                Cloud9     ahq eSports Club          1          0
 4                Cloud9        EDward Gaming          1          0
 5                Cloud9        SK Telecom T1          0          1
 6         EDward Gaming     ahq eSports Club          0          1
 7         EDward Gaming               Cloud9          1          0
 8         EDward Gaming        SK Telecom T1          0          1
 9    Fenerbahçe Esports           G2 Esports          0          1
 10   Fenerbahçe Esports  Royal Never Give Up          0          1
 11   Fenerbahçe Esports       Samsung Galaxy          0          1
 12         Flash Wolves       Misfits Gaming          0          1
 13         Flash Wolves              Team WE          0          1
 14         Flash Wolves                  TSM          0          1
 15               Fnatic     GIGABYTE Marines          0          1
 16               Fnatic            Immortals          1          0
 17               Fnatic            Immortals          1          0
 18               Fnatic       Longzhu Gaming          0          1
 19           G2 Esports   Fenerbahçe Esports          1          0
 20           G2 Esports  Royal Never Give Up          1          0
 21           G2 Esports       Samsung Galaxy          0          1
 22     GIGABYTE Marines               Fnatic          0          1
 23     GIGABYTE Marines               Fnatic          0          1
 24     GIGABYTE Marines            Immortals          0          1
 25     GIGABYTE Marines       Longzhu Gaming          0          1
 26            Immortals               Fnatic          1          0
 27            Immortals     GIGABYTE Marines          0          1
 28            Immortals       Longzhu Gaming          0          1
 29       Longzhu Gaming               Fnatic          1          0
 30       Longzhu Gaming     GIGABYTE Marines          1          0
 31       Longzhu Gaming            Immortals          1          0
 32       Longzhu Gaming       Samsung Galaxy          0          3
 33       Misfits Gaming         Flash Wolves          1          0
 34       Misfits Gaming              Team WE          0          1
 35       Misfits Gaming                  TSM          1          0
 36       Misfits Gaming                  TSM          1          0
 37  Royal Never Give Up   Fenerbahçe Esports          1          0
 38  Royal Never Give Up               Fnatic          3          1
 39  Royal Never Give Up           G2 Esports          1          0
 40  Royal Never Give Up       Samsung Galaxy          1          0
 41       Samsung Galaxy   Fenerbahçe Esports          1          0
 42       Samsung Galaxy           G2 Esports          1          0
 43       Samsung Galaxy  Royal Never Give Up          0          1
 44       Samsung Galaxy              Team WE          3          1
 45        SK Telecom T1     ahq eSports Club          1          0
 46        SK Telecom T1               Cloud9          1          0
 47        SK Telecom T1        EDward Gaming          1          0
 48        SK Telecom T1       Misfits Gaming          3          2
 49        SK Telecom T1  Royal Never Give Up          3          2
 50        SK Telecom T1       Samsung Galaxy          0          3
 51              Team WE               Cloud9          3          2
 52              Team WE         Flash Wolves          1          0
 53              Team WE       Misfits Gaming          1          0
 54              Team WE                  TSM          1          0
 55                  TSM         Flash Wolves          0          1
 56                  TSM       Misfits Gaming          1          0
 57                  TSM              Team WE          1          0

               Tab
 0           Day 2
 1           Day 8
 2           Day 8
 3           Day 8
 4           Day 3
 5           Day 8
 6           Day 1
 7           Day 8
 8           Day 2
 9           Day 6
 10          Day 6
 11          Day 4
 12          Day 3
 13          Day 7
 14          Day 2
 15          Day 1
 16          Day 5
 17          Day 5
 18          Day 4
 19          Day 3
 20          Day 6
 21          Day 1
 22          Day 5
 23          Day 5
 24          Day 4
 25          Day 5
 26          Day 2
 27          Day 5
 28          Day 5
 29          Day 5
 30          Day 2
 31          Day 1
 32  Quarterfinals
 33          Day 7
 34          Day 7
 35          Day 4
 36          Day 7
 37          Day 1
 38  Quarterfinals
 39          Day 4
 40          Day 6
 41          Day 6
 42          Day 6
 43          Day 3
 44     Semifinals
 45          Day 3
 46          Day 1
 47          Day 8
 48  Quarterfinals
 49     Semifinals
 50         Finals
 51  Quarterfinals
 52          Day 4
 53          Day 2
 54          Day 7
 55          Day 7
 56          Day 7
 57          Day 3  ,
 2018:                   Team1                Team2 Team1Score Team2Score  \
 0           100 Thieves               Fnatic          0          1
 1           100 Thieves                G-Rex          1          0
 2           100 Thieves      Invictus Gaming          0          1
 3        Afreeca Freecs               Cloud9          0          3
 4        Afreeca Freecs         Flash Wolves          1          0
 5        Afreeca Freecs           G2 Esports          0          1
 6        Afreeca Freecs     Phong Vũ Buffalo          1          0
 7                Cloud9               Fnatic          0          3
 8                Cloud9                Gen.G          0          1
 9                Cloud9  Royal Never Give Up          1          0
 10               Cloud9        Team Vitality          1          0
 11        EDward Gaming           KT Rolster          1          0
 12        EDward Gaming             MAD Team          1          0
 13        EDward Gaming          Team Liquid          0          1
 14         Flash Wolves       Afreeca Freecs          1          0
 15         Flash Wolves           G2 Esports          0          1
 16         Flash Wolves           G2 Esports          1          0
 17         Flash Wolves     Phong Vũ Buffalo          0          1
 18               Fnatic          100 Thieves          1          0
 19               Fnatic        EDward Gaming          3          1
 20               Fnatic                G-Rex          1          0
 21               Fnatic      Invictus Gaming          0          1
 22               Fnatic      Invictus Gaming          0          3
 23               Fnatic      Invictus Gaming          1          0
 24                G-Rex          100 Thieves          0          1
 25                G-Rex               Fnatic          0          1
 26                G-Rex      Invictus Gaming          0          1
 27           G2 Esports       Afreeca Freecs          0          1
 28           G2 Esports         Flash Wolves          1          0
 29           G2 Esports      Invictus Gaming          0          3
 30           G2 Esports     Phong Vũ Buffalo          1          0
 31                Gen.G               Cloud9          0          1
 32                Gen.G  Royal Never Give Up          0          1
 33                Gen.G        Team Vitality          0          1
 34      Invictus Gaming          100 Thieves          1          0
 35      Invictus Gaming               Fnatic          0          1
 36      Invictus Gaming                G-Rex          1          0
 37           KT Rolster        EDward Gaming          1          0
 38           KT Rolster      Invictus Gaming          2          3
 39           KT Rolster             MAD Team          1          0
 40           KT Rolster          Team Liquid          1          0
 41             MAD Team        EDward Gaming          0          1
 42             MAD Team           KT Rolster          0          1
 43             MAD Team          Team Liquid          0          1
 44     Phong Vũ Buffalo       Afreeca Freecs          0          1
 45     Phong Vũ Buffalo         Flash Wolves          0          1
 46     Phong Vũ Buffalo           G2 Esports          1          0
 47  Royal Never Give Up               Cloud9          1          0
 48  Royal Never Give Up               Cloud9          1          0
 49  Royal Never Give Up           G2 Esports          2          3
 50  Royal Never Give Up                Gen.G          1          0
 51  Royal Never Give Up        Team Vitality          1          0
 52          Team Liquid        EDward Gaming          0          1
 53          Team Liquid           KT Rolster          0          1
 54          Team Liquid             MAD Team          1          0
 55        Team Vitality               Cloud9          0          1
 56        Team Vitality                Gen.G          1          0
 57        Team Vitality  Royal Never Give Up          1          0

               Tab
 0           Day 2
 1           Day 3
 2           Day 8
 3   Quarterfinals
 4           Day 6
 5           Day 1
 6           Day 4
 7      Semifinals
 8           Day 3
 9           Day 5
 10          Day 5
 11          Day 7
 12          Day 1
 13          Day 7
 14          Day 2
 15    Tiebreakers
 16          Day 6
 17          Day 6
 18          Day 8
 19  Quarterfinals
 20          Day 8
 21          Day 3
 22         Finals
 23    Tiebreakers
 24          Day 8
 25          Day 4
 26          Day 8
 27          Day 6
 28          Day 4
 29     Semifinals
 30          Day 6
 31          Day 5
 32          Day 2
 33          Day 1
 34          Day 4
 35          Day 8
 36          Day 2
 37          Day 4
 38  Quarterfinals
 39          Day 7
 40          Day 1
 41          Day 7
 42          Day 3
 43          Day 7
 44          Day 6
 45          Day 1
 46          Day 2
 47          Day 1
 48    Tiebreakers
 49  Quarterfinals
 50          Day 5
 51          Day 3
 52          Day 3
 53          Day 7
 54          Day 4
 55          Day 2
 56          Day 5
 57          Day 5  ,
 2019:                     Team1                  Team2 Team1Score Team2Score  \
 0        ahq eSports Club          DAMWON Gaming          0          1
 1        ahq eSports Club        Invictus Gaming          0          1
 2        ahq eSports Club            Team Liquid          0          1
 3                  Cloud9             G2 Esports          0          1
 4                  Cloud9  Griffin (Korean Team)          0          1
 5                  Cloud9     Hong Kong Attitude          1          0
 6           Clutch Gaming                 Fnatic          0          1
 7           Clutch Gaming    Royal Never Give Up          0          1
 8           Clutch Gaming          SK Telecom T1          0          1
 9           DAMWON Gaming       ahq eSports Club          1          0
 10          DAMWON Gaming             G2 Esports          1          3
 11          DAMWON Gaming        Invictus Gaming          1          0
 12          DAMWON Gaming            Team Liquid          0          1
 13                 Fnatic          Clutch Gaming          1          0
 14                 Fnatic    Royal Never Give Up          1          0
 15                 Fnatic          SK Telecom T1          0          1
 16        FunPlus Phoenix                 Fnatic          3          1
 17        FunPlus Phoenix            GAM Esports          1          0
 18        FunPlus Phoenix                 J Team          1          0
 19        FunPlus Phoenix                 Splyce          1          0
 20        FunPlus Phoenix                 Splyce          1          0
 21             G2 Esports                 Cloud9          1          0
 22             G2 Esports        FunPlus Phoenix          0          3
 23             G2 Esports  Griffin (Korean Team)          0          1
 24             G2 Esports  Griffin (Korean Team)          0          1
 25             G2 Esports     Hong Kong Attitude          1          0
 26             G2 Esports          SK Telecom T1          3          1
 27            GAM Esports        FunPlus Phoenix          0          1
 28            GAM Esports                 J Team          0          1
 29            GAM Esports                 Splyce          0          1
 30  Griffin (Korean Team)                 Cloud9          1          0
 31  Griffin (Korean Team)             G2 Esports          0          1
 32  Griffin (Korean Team)     Hong Kong Attitude          1          0
 33  Griffin (Korean Team)        Invictus Gaming          1          3
 34     Hong Kong Attitude                 Cloud9          0          1
 35     Hong Kong Attitude             G2 Esports          0          1
 36     Hong Kong Attitude  Griffin (Korean Team)          0          1
 37        Invictus Gaming       ahq eSports Club          1          0
 38        Invictus Gaming          DAMWON Gaming          0          1
 39        Invictus Gaming        FunPlus Phoenix          1          3
 40        Invictus Gaming            Team Liquid          1          0
 41                 J Team        FunPlus Phoenix          1          0
 42                 J Team            GAM Esports          0          1
 43                 J Team                 Splyce          0          1
 44    Royal Never Give Up          Clutch Gaming          1          0
 45    Royal Never Give Up                 Fnatic          1          0
 46    Royal Never Give Up          SK Telecom T1          0          1
 47          SK Telecom T1          Clutch Gaming          1          0
 48          SK Telecom T1                 Fnatic          0          1
 49          SK Telecom T1    Royal Never Give Up          1          0
 50          SK Telecom T1                 Splyce          3          1
 51                 Splyce        FunPlus Phoenix          1          0
 52                 Splyce            GAM Esports          1          0
 53                 Splyce                 J Team          0          1
 54            Team Liquid       ahq eSports Club          1          0
 55            Team Liquid          DAMWON Gaming          0          1
 56            Team Liquid        Invictus Gaming          0          1

               Tab
 0           Day 2
 1           Day 8
 2           Day 3
 3           Day 6
 4           Day 4
 5           Day 2
 6           Day 7
 7           Day 7
 8           Day 4
 9           Day 8
 10  Quarterfinals
 11          Day 8
 12          Day 1
 13          Day 2
 14          Day 7
 15          Day 1
 16  Quarterfinals
 17          Day 4
 18          Day 5
 19          Day 3
 20    Tiebreakers
 21          Day 3
 22         Finals
 23          Day 6
 24    Tiebreakers
 25          Day 6
 26     Semifinals
 27          Day 5
 28          Day 5
 29          Day 1
 30          Day 6
 31          Day 2
 32          Day 3
 33  Quarterfinals
 34          Day 6
 35          Day 4
 36          Day 6
 37          Day 1
 38          Day 3
 39     Semifinals
 40          Day 8
 41          Day 1
 42          Day 3
 43          Day 5
 44          Day 1
 45          Day 4
 46          Day 7
 47          Day 7
 48          Day 7
 49          Day 2
 50  Quarterfinals
 51          Day 5
 52          Day 5
 53          Day 4
 54          Day 8
 55          Day 8
 56          Day 2  ,
 2020:                     Team1                  Team2 Team1Score Team2Score  \
 0           DAMWON Gaming                    DRX          3          0
 1           DAMWON Gaming              JD Gaming          1          0
 2           DAMWON Gaming              PSG Talon          1          0
 3           DAMWON Gaming  Rogue (European Team)          1          0
 4                     DRX               FlyQuest          1          0
 5                     DRX            Top Esports          0          1
 6                     DRX   Unicorns of Love.CIS          1          0
 7                FlyQuest                    DRX          0          1
 8                FlyQuest            Top Esports          0          1
 9                FlyQuest   Unicorns of Love.CIS          1          0
 10                 Fnatic                  Gen.G          1          0
 11                 Fnatic             LGD Gaming          1          0
 12                 Fnatic                    TSM          1          0
 13             G2 Esports          DAMWON Gaming          1          3
 14             G2 Esports          Machi Esports          1          0
 15             G2 Esports                 Suning          0          1
 16             G2 Esports                 Suning          1          0
 17             G2 Esports            Team Liquid          0          1
 18                  Gen.G                 Fnatic          1          0
 19                  Gen.G             G2 Esports          0          3
 20                  Gen.G             LGD Gaming          1          0
 21                  Gen.G                    TSM          1          0
 22              JD Gaming          DAMWON Gaming          1          0
 23              JD Gaming              PSG Talon          0          1
 24              JD Gaming  Rogue (European Team)          1          0
 25             LGD Gaming                 Fnatic          1          0
 26             LGD Gaming                  Gen.G          0          1
 27             LGD Gaming                    TSM          1          0
 28          Machi Esports             G2 Esports          0          1
 29          Machi Esports                 Suning          0          1
 30          Machi Esports            Team Liquid          1          0
 31              PSG Talon          DAMWON Gaming          0          1
 32              PSG Talon              JD Gaming          0          1
 33              PSG Talon  Rogue (European Team)          1          0
 34  Rogue (European Team)          DAMWON Gaming          0          1
 35  Rogue (European Team)              JD Gaming          0          1
 36  Rogue (European Team)              PSG Talon          1          0
 37                 Suning          DAMWON Gaming          1          3
 38                 Suning             G2 Esports          1          0
 39                 Suning              JD Gaming          3          1
 40                 Suning          Machi Esports          1          0
 41                 Suning            Team Liquid          0          1
 42            Team Liquid             G2 Esports          0          1
 43            Team Liquid          Machi Esports          1          0
 44            Team Liquid                 Suning          0          1
 45            Top Esports                    DRX          1          0
 46            Top Esports               FlyQuest          0          1
 47            Top Esports                 Fnatic          3          2
 48            Top Esports                 Suning          1          3
 49            Top Esports   Unicorns of Love.CIS          1          0
 50                    TSM                 Fnatic          0          1
 51                    TSM                  Gen.G          0          1
 52                    TSM             LGD Gaming          0          1
 53   Unicorns of Love.CIS                    DRX          0          1
 54   Unicorns of Love.CIS               FlyQuest          0          1
 55   Unicorns of Love.CIS            Top Esports          0          1


In [109]:
def WhoWon(row):
    if row["Team1Score"]>row["Team2Score"]: return row["Team1"]
    else: return row["Team2"]

In [115]:
df_KnockoutStage = dict() # Will contain the matches for the quarterfinals,semifinals and finals
for year in range(2017,2023):
    dict_groups_data[year]["Wins"] = 0
    df_KnockoutStage[year] = pd.DataFrame([], columns=dict_Worlds_data[year].columns)
    for index,row in dict_Worlds_data[year].iterrows():
        if (row.Tab not in ['Quarterfinals', 'Semifinals', 'Finals']):
            winner_row = dict_groups_data[year].Team == WhoWon(row)
            dict_groups_data[year].Wins[winner_row] += 1
        else:
            df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
    df_KnockoutStage[year]["Winner"] = df_KnockoutStage[year].apply(WhoWon,axis=1)

C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_groups_data[year].Wins[winner_row] += 1
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
C:\Users\vivia\AppData\Local\Temp\ipykernel_8852\3970410261.py:8: SettingWithCopyWarning:

In [94]:
df_KnockoutStage[2022]

,Team1,Team2,Team1Score,Team2Score,Tab,Winner
9,DRX,EDward Gaming,3,2,Quarterfinals,DRX
35,Gen.G,DRX,1,3,Semifinals,DRX
36,Gen.G,DWG KIA,3,2,Quarterfinals,Gen.G
42,JD Gaming,Rogue (European Team),3,0,Quarterfinals,JD Gaming
43,JD Gaming,T1,1,3,Semifinals,T1
51,T1,DRX,2,3,Finals,DRX
54,T1,Royal Never Give Up,3,0,Quarterfinals,T1

In [ ]:
df_Worlds_Winners = dict() # Will contain the matches for the quarterfinals,semifinals and finals
for year in range(2015,2023):
    dict_groups_data[year]["Wins"] = 0
    df_KnockoutStage[year] = pd.DataFrame([], columns=dict_Worlds_data[year].columns)
    for index,row in dict_Worlds_data[year].iterrows():
        if (row.Tab not in ['Quarterfinals', 'Semifinals', 'Finals']):
            winner_row = dict_groups_data[year].Team == WhoWon(row)
            dict_groups_data[year].Wins[winner_row] += 1
        else:
            df_KnockoutStage[year] = df_KnockoutStage[year].append(row)
    df_KnockoutStage[year]["Winner"] = df_KnockoutStage[year].apply(WhoWon,axis=1)